export interface SectionDef {
  code: string;
  name: string;
}

// Official ARRL/RAC contest section list (85 sections), fetched from
// https://contests.arrl.org/contestmultipliers.php?a=wve
export const SECTIONS: SectionDef[] = [
  { code: 'CO', name: 'Colorado' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MO', name: 'Missouri' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'EMA', name: 'Eastern Massachusetts' },
  { code: 'ME', name: 'Maine' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'VT', name: 'Vermont' },
  { code: 'WMA', name: 'Western Massachusetts' },
  { code: 'ENY', name: 'Eastern New York' },
  { code: 'NLI', name: 'New York City-Long Island' },
  { code: 'NNJ', name: 'Northern New Jersey' },
  { code: 'NNY', name: 'Northern New York' },
  { code: 'SNJ', name: 'Southern New Jersey' },
  { code: 'WNY', name: 'Western New York' },
  { code: 'DE', name: 'Delaware' },
  { code: 'EPA', name: 'Eastern Pennsylvania' },
  { code: 'MDC', name: 'Maryland-DC' },
  { code: 'WPA', name: 'Western Pennsylvania' },
  { code: 'AL', name: 'Alabama' },
  { code: 'GA', name: 'Georgia' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'NFL', name: 'Northern Florida' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SFL', name: 'Southern Florida' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'VA', name: 'Virginia' },
  { code: 'VI', name: 'US Virgin Islands' },
  { code: 'WCF', name: 'West Central Florida' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NTX', name: 'North Texas' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'STX', name: 'South Texas' },
  { code: 'WTX', name: 'West Texas' },
  { code: 'EB', name: 'East Bay' },
  { code: 'LAX', name: 'Los Angeles' },
  { code: 'ORG', name: 'Orange' },
  { code: 'PAC', name: 'Pacific' },
  { code: 'SB', name: 'Santa Barbara' },
  { code: 'SCV', name: 'Santa Clara Valley' },
  { code: 'SDG', name: 'San Diego' },
  { code: 'SF', name: 'San Francisco' },
  { code: 'SJV', name: 'San Joaquin Valley' },
  { code: 'SV', name: 'Sacramento Valley' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'EWA', name: 'Eastern Washington' },
  { code: 'ID', name: 'Idaho' },
  { code: 'MT', name: 'Montana' },
  { code: 'NV', name: 'Nevada' },
  { code: 'OR', name: 'Oregon' },
  { code: 'UT', name: 'Utah' },
  { code: 'WWA', name: 'Western Washington' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'MI', name: 'Michigan' },
  { code: 'OH', name: 'Ohio' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'AB', name: 'Alberta' },
  { code: 'BC', name: 'British Columbia' },
  { code: 'GH', name: 'Ontario Golden Horseshoe' },
  { code: 'MB', name: 'Manitoba' },
  { code: 'NB', name: 'New Brunswick' },
  { code: 'NL', name: 'Newfoundland and Labrador' },
  { code: 'NS', name: 'Nova Scotia' },
  { code: 'ONE', name: 'Ontario East' },
  { code: 'ONN', name: 'Ontario North' },
  { code: 'ONS', name: 'Ontario South' },
  { code: 'PE', name: 'Prince Edward Island' },
  { code: 'QC', name: 'Quebec' },
  { code: 'SK', name: 'Saskatchewan' },
  { code: 'TER', name: 'Territories' },
];

export const DX_SECTION = 'DX';

export const SECTION_CODES: string[] = [...SECTIONS.map((s) => s.code), DX_SECTION];

export function isValidSectionCode(code: string): boolean {
  const upper = code.toUpperCase();
  return upper === DX_SECTION || SECTIONS.some((s) => s.code === upper);
}
